export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_END = "FETCH_POSTS_END";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_POST = "FETCH_POST";
